### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by ThomasGaubert** [EnsemblePlayer/chorus#31]
Implement Material Design as closely as possible to Google's specifications: http://www.google.com/design/spec/material-design/introduction.html

**Comment by ThomasGaubert** [comment]
This is currently taking precedence over other enhancements. Current focus is to port all implemented features to the new design (see `newapp` directory).

**Comment by abauer** [comment]
List for this issue?

**Comment by ThomasGaubert** [comment]
Yeah, I'll add one _eventually_.

**Comment by ThomasGaubert** [comment]
A large amount of the work here is done. Future additions and changes should incorporate Material Design.
